version: "3.9"

services:
  orders:
    build:
      dockerfile: src/Showcase.Orders/DOCKERFILE
      target: release-env
      context: src/Showcase.Orders
      
    depends_on:
      - db

  db: 
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  flyway:
    image: "flyway/flyway"
    command: -url=jdbc:postgresql://db/ -schemas=public -user=postgres -password=mysecretpassword migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
